import type { Metadata } from "next";
import Header from "@/components/header";
// import Footer from "@/components/footer";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className="font-[Vazir-Medium]">
      <body
        className=""
      >
        <Header />
          {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
